### ISSUE TITLE
'Armature' has no attribute 'rigify_layers'

### ISSUE THREAD

**Issue by AgentKirin** [Arminando/GameRig#35]
So, I'm rigging a horse for a game and I figured I'd give the game horse rig in here a try. However, when I attempt to add it, I get an error that says "AttributeError: 'Armature' has no attribute 'rigify_layers'. Did you mean 'rigify_colors'?"

A quick search tells me it might be an incompatibility with my version of Blender - I'm using 4.5.3 LTS, while the latest release is made for 3.5/3.6. I do see the notes saying that 4.0+ compatibility is being worked on. Is it in a state where I can download what's currently there and have it work? If not, no rush, just figured I'd ask.

**Comment by abuyamman87-maker** [comment]
Having the same issue, i am trying to create a basic human game rig and the error is same

**Comment by Arminando** [comment]
Hey all, sorry for the wait.
There is a new release now which is updated to work with 4.5.4 and 5.0.
And making rigs is a lot more streamlined now. Check it out and please continue reporting bugs. I appreciate you doing that and using the extension.
